import type { EhelpState, Permission, Role } from "./types"

export const DEFAULT_RBAC: Record<Role, Permission[]> = {
  "dswd-admin": [
    "view-analytics",
    "manage-templates",
    "manage-rbac",
    "approve-accounts",
    "view-audit",
  ],
  "satellite-admin": [
    "view-analytics",
    "customize-templates",
    "manage-region-rbac",
    "register-accounts",
    "approve-accounts",
  ],
  approver: [
    "approve-applications",
    "release-disbursements",
    "act-recommendations",
  ],
  evaluator: [
    "evaluate-applications",
    "register-customers",
    "submit-recommendations",
  ],
}

export const SEED: EhelpState = {
  session: { role: "dswd-admin", region: "NCR" },
  rbac: DEFAULT_RBAC,
  customers: [
    {
      id: "CUS-0001",
      name: "Maria Reyes",
      region: "NCR",
      philsysId: "PSN-6301-2214-9087",
      idRecords: true,
      faceScan: "Verified",
      disbursementPref: "E-wallet",
      lastDisbursedAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "CUS-0002",
      name: "Jose Bautista",
      region: "Region III",
      philsysId: "PSN-1183-0042-5521",
      idRecords: true,
      faceScan: "Verified",
      disbursementPref: "Bank",
    },
    {
      id: "CUS-0003",
      name: "Ana Dela Cruz",
      region: "Region VII",
      philsysId: "PSN-7745-9910-3306",
      idRecords: true,
      faceScan: "Pending",
      disbursementPref: "—",
    },
  ],
  dependents: [
    {
      id: "DEP-0001",
      name: "Lito Reyes",
      customerId: "CUS-0001",
      kind: "Dependent",
      relationshipRecord: true,
      notarizedLetter: false,
      status: "Active",
    },
    {
      id: "DEP-0002",
      name: "Carmen Bautista",
      customerId: "CUS-0002",
      kind: "Guarantor",
      relationshipRecord: false,
      notarizedLetter: false,
      status: "Pending Validation",
    },
  ],
  applications: [
    {
      id: "APP-0001",
      customerId: "CUS-0001",
      templateId: "TPL-AICS",
      region: "NCR",
      status: "Approved",
      priority: "High",
      filedBy: "Evaluator",
      note: "Medical assistance, endorsed by satellite office",
      updatedAt: "2026-07-18T02:10:00.000Z",
    },
    {
      id: "APP-0002",
      customerId: "CUS-0002",
      templateId: "TPL-AKAP",
      region: "Region III",
      status: "For Approval",
      priority: "Medium",
      filedBy: "Customer",
      updatedAt: "2026-07-19T06:45:00.000Z",
    },
    {
      id: "APP-0003",
      customerId: "CUS-0003",
      templateId: "TPL-AICS",
      region: "Region VII",
      status: "Submitted",
      priority: "Low",
      filedBy: "Customer",
      updatedAt: "2026-07-20T11:20:00.000Z",
    },
  ],
  templates: [
    {
      id: "TPL-AICS",
      name: "AICS Cash Assistance",
      program: "DSWD · AICS",
      cooldownDays: 90,
      requirements: "Valid ID, barangay certificate, case study report",
      active: true,
    },
    {
      id: "TPL-AKAP",
      name: "AKAP Aid Package",
      program: "DSWD · AKAP",
      cooldownDays: 60,
      requirements: "Valid ID, proof of income below threshold",
      active: true,
    },
    {
      id: "TPL-ESKWELA",
      name: "Tulong Eskwela Grant",
      program: "DSWD · Tulong Eskwela",
      cooldownDays: 180,
      requirements: "Valid ID, school enrolment certificate",
      active: false,
    },
  ],
  overrides: [
    {
      templateId: "TPL-AICS",
      region: "Region VII",
      eligibilityNote: "Typhoon-affected barangays prioritized",
      cooldownDays: 45,
    },
  ],
  recommendations: [
    {
      id: "REC-0001",
      subject: "APP-0002",
      priority: "High",
      submittedBy: "Regional Evaluator",
      region: "Region III",
      status: "Open",
      note: "Household displaced by flooding — recommend priority lane",
    },
  ],
  accounts: [
    {
      id: "ACC-0001",
      name: "Grace Villanueva",
      role: "dswd-admin",
      region: "Central",
      status: "Active",
      pinAgeDays: 12,
      otpEnabled: true,
      faceEnrolled: true,
    },
    {
      id: "ACC-0002",
      name: "Paolo Mendoza",
      role: "satellite-admin",
      region: "NCR",
      status: "Active",
      pinAgeDays: 95,
      otpEnabled: true,
      faceEnrolled: true,
    },
    {
      id: "ACC-0003",
      name: "Irene Salazar",
      role: "approver",
      region: "Region III",
      status: "Active",
      pinAgeDays: 44,
      otpEnabled: true,
      faceEnrolled: false,
    },
    {
      id: "ACC-0004",
      name: "Marco Lim",
      role: "evaluator",
      region: "Region VII",
      status: "Pending Approval",
      pinAgeDays: 0,
      otpEnabled: false,
      faceEnrolled: false,
    },
  ],
  audit: [
    {
      id: "AUD-0003",
      ts: "2026-07-20T11:20:00.000Z",
      actor: "Customer · CUS-0003",
      action: "application.submitted",
      detail: "APP-0003 filed for AICS Cash Assistance (Region VII)",
    },
    {
      id: "AUD-0002",
      ts: "2026-07-19T06:45:00.000Z",
      actor: "Regional Evaluator · Region III",
      action: "application.for-approval",
      detail: "APP-0002 endorsed to approver queue",
    },
    {
      id: "AUD-0001",
      ts: "2026-07-18T02:10:00.000Z",
      actor: "Regional Approver · NCR",
      action: "application.approved",
      detail: "APP-0001 approved for disbursement",
    },
  ],
}
